<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIqx4Yl2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIqx4Yl2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIqx4Yl2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIqx4Yl2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIqx4Yl2\App_KernelDevDebugContainer([
    'container.build_hash' => 'Iqx4Yl2',
    'container.build_id' => 'fdcc2107',
    'container.build_time' => 1657691462,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIqx4Yl2');
